[package]
name = "block-execution"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# reth dependencies
reth.workspace = true
reth-primitives = { path = "../../crates/primitives" }
reth-primitives-traits = { path = "../../crates/primitives-traits" }
reth-ethereum-primitives = { path = "../../crates/ethereum/primitives" }
reth-ethereum-engine-primitives = { path = "../../crates/ethereum/engine-primitives" }
reth-evm = { path = "../../crates/evm" }
reth-revm = { path = "../../crates/revm" }
reth-db = { path = "../../crates/storage/db", features = ["test-utils"] }
reth-db-common = { path = "../../crates/storage/db-common" }
reth-provider = { path = "../../crates/storage/provider" }
reth-chainspec = { path = "../../crates/chainspec" }
reth-node-ethereum = { path = "../../crates/ethereum/node" }
reth-trie = { path = "../../crates/trie/trie" }
reth-e2e-test-utils = { path = "../../crates/e2e-test-utils" }
reth-node-api = { path = "../../crates/node/api" }
reth-node-core = { path = "../../crates/node/core" }
futures = "0.3"

# external dependencies
alloy-primitives = { workspace = true }
alloy-rpc-types-engine = { workspace = true }
alloy-consensus = { workspace = true }
alloy-genesis = { workspace = true }
alloy-chains = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-network = { workspace = true }
alloy-signer = { workspace = true }
alloy-eips = { workspace = true }
k256 = { version = "0.13", features = ["ecdsa"] }
tokio = { version = "1.0", features = ["rt", "rt-multi-thread"] }
revm = { workspace = true }
eyre = { workspace = true }
serde_json = { workspace = true }
rayon = "1.8"
reqwest = { version = "0.11", features = ["json"] } 